### ISSUE TITLE
Windows line ending problem

### ISSUE THREAD

**Issue by jscissr** [Sammons/exec-glob#1]
When trying to use `exec-glob` on linux, you get this error:

```
': No such file or directory
```

This is because the files published to npm use CRLF line endings. When trying to execute `bin/cmd.js`, the shebang parser does not understand CRs.

Please change the line endings to linux (LF) and publish a new version to npm.

**Comment by Sammons** [comment]
@jscissr I haven't checked out this project in quite some time but I will take a look at this. What exactly are you trying to use it for? I want to be sure that if I open it up and fix it that it can serve your use-case.

Cheers

**Comment by jscissr** [comment]
I'm using it [here](https://github.com/ipfs/browserify-zlib/pull/19). The build that failed because of this was https://travis-ci.org/ipfs/browserify-zlib/jobs/151308463, but I already used a workaround: `node node_modules/exec-glob ...` instead of `exec-glob ...`.

So I don't really need this anymore, but still it's quite an easy fix. All you really have to do is change the line endings of `bin/cmd.js` to linux, run `npm version patch && npm publish`.

**Comment by Sammons** [comment]
it works for me now on my mac after republishing (it didn't before due to the \r).

**Comment by jscissr** [comment]
Thanks! :+1:
